// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJNz2sS5hZq9Hgs_TNtXf3R8h7yAw7-cM',
    appId: '1:438447775400:web:6a40acc79140171ca82c9d',
    messagingSenderId: '438447775400',
    projectId: 'todo-pomodoro-3ed9c',
    authDomain: 'todo-pomodoro-3ed9c.firebaseapp.com',
    storageBucket: 'todo-pomodoro-3ed9c.firebasestorage.app',
    measurementId: 'G-70JGYRFY4C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKblc0v8zvRqYm32ZkZLAR3-_jm409qPk',
    appId: '1:438447775400:android:9560f90d150b126ea82c9d',
    messagingSenderId: '438447775400',
    projectId: 'todo-pomodoro-3ed9c',
    storageBucket: 'todo-pomodoro-3ed9c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEB83NZpor_dHHI51yf-RWH5z71cZRmQ8',
    appId: '1:438447775400:ios:ebf2e951abda596aa82c9d',
    messagingSenderId: '438447775400',
    projectId: 'todo-pomodoro-3ed9c',
    storageBucket: 'todo-pomodoro-3ed9c.firebasestorage.app',
    iosBundleId: 'com.example.taskflowSuite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEB83NZpor_dHHI51yf-RWH5z71cZRmQ8',
    appId: '1:438447775400:ios:ebf2e951abda596aa82c9d',
    messagingSenderId: '438447775400',
    projectId: 'todo-pomodoro-3ed9c',
    storageBucket: 'todo-pomodoro-3ed9c.firebasestorage.app',
    iosBundleId: 'com.example.taskflowSuite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJNz2sS5hZq9Hgs_TNtXf3R8h7yAw7-cM',
    appId: '1:438447775400:web:9d39f384883a1653a82c9d',
    messagingSenderId: '438447775400',
    projectId: 'todo-pomodoro-3ed9c',
    authDomain: 'todo-pomodoro-3ed9c.firebaseapp.com',
    storageBucket: 'todo-pomodoro-3ed9c.firebasestorage.app',
    measurementId: 'G-59T151J7H5',
  );
}
